version: '3.9'
services:
  app:
    build: .
    ports:
      - '${PORT}:5000'
    env_file:
      - ./.env
    depends_on:
      - db
      - redis_server
  db:
    container_name: 'expense-app-db'
    image: postgres
    restart: always
    expose:
      - 5432
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - path: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data/
  test_db:
    container_name: 'expense-app-test_db'
    image: postgres
    restart: always
    expose:
      - 5432
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - path: .env.test
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_test_data:/var/lib/postgresql/data/
  redis_server:
    container_name: 'expense-app-redis'
    image: redis
    restart: always
    env_file:
      - path: ./.env
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/data/

volumes:
  postgres:
  redis_data:
