version: "3.9"
services:
  db:
    container_name: "expense-app-db"
    image: postgres
    restart: always
    expose:
      - 5432
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - path: ./.env
    volumes:
      - postgres:/var/lib/postgresql/data/

volumes:
  postgres:
